version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g typescript
      - npm install --force
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - node ./dist/server.js

artifacts:
  files:
    - package-lock.json
    - package.json
    - 'dist/**/*'
    - '.platform/**/*' # AWS Elastic Beanstalk configuration files
    - '.ebextensions/**/*' # AWS Elastic Beanstalk configuration files
  discard-paths: no
